/** @type {import('ts-jest').JestConfigWithTsJest} */
module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'jsdom',
  moduleNameMapper: {
    "\\.(png|jpg|jpeg|gif|svg)$": "<rootDir>/tests/mocks/fileMock.js",
    "^@/(.*)$": "<rootDir>/app/src/$1",
    "^../(services|models|constants|config|errors)/(.*)\\.js$": "<rootDir>/server/$1/$2.ts",
    "^@/types.js$": "<rootDir>/server/$1.ts",
    "^../../shared/utils/regexPatterns\\.js$": "<rootDir>/shared/utils/regexPatterns.ts",
    "^../../utils/authUtils/jwtUtils.js$": "<rootDir>/utils/authUtils/jwtUtils.ts",
    "^../../server/errors/customErrors.js$": "<rootDir>/server/errors/customErrors.ts",
    "^../../server/constants/internalErrorMessages.js$": "<rootDir>/server/constants/internalErrorMessages.ts",
    "^./../../shared/utils/regexPatterns\\.js$": "<rootDir>/shared/utils/regexPatterns.ts",
    "^../../shared/constants/responseMessages.js$": "<rootDir>/shared/constants/responseMessages.ts",
    "^./location.js$": "<rootDir>/server/models/location.ts",
    "^../utils/jwt.js$": "<rootDir>/server/utils/jwt.ts",
    "^../utils/time.js$": "<rootDir>/server/utils/time.ts",
    "^../../shared/utils/dateValidations.js$": "<rootDir>/shared/utils/dateValidations.ts",
    "^../../server/constants/validationErrorMessages.js$": "<rootDir>/server/constants/validationErrorMessages.ts",
    "^./regexPatterns.js$": "<rootDir>/shared/utils/regexPatterns.ts",
    "\\.(css|less|scss|sass)$": "identity-obj-proxy",
    "@@/utils/dateUtils": "<rootDir>/shared/utils/dateUtils.ts",
    "^./transtationUtil.js$": "<rootDir>/app/src/utils/transtationUtil.tsx",
    "^../../shared/constants/userRoles\\.js$": "<rootDir>/shared/constants/userRoles.ts",
    "^../chatIntegration/chatService\\.js$": "<rootDir>/server//chatIntegration/chatService.ts",
    "^./types\\.js$": "<rootDir>/server/chatIntegration/types.ts",
    "^./messages\\.js$": "<rootDir>/server/chatIntegration/messages.ts",
    "^./chatRoom\\.js$": "<rootDir>/server/chatIntegration/chatRoom.ts",
    "^./constants\\.js$": "<rootDir>/server/chatIntegration/constants.ts",
    "^../../shared/utils/dateUtils.js$": "<rootDir>/shared/utils/dateUtils.ts",
    "^./logger.js$": "<rootDir>/server/config/logger.ts",
    "^./eventService.js$": "<rootDir>/server/services/eventService.ts",
    "../types.js": "<rootDir>/server/types.ts",
    "^../utils/(cookie|environmentVariablesParseUtils|jwt|time).js$": "<rootDir>/server/utils/$1.ts",
    "^../chatIntegration/(.*).js": "<rootDir>/server/chatIntegration/$1.ts",
    "../../server/config/config.js": "<rootDir>/server/config/config.ts",
    "^./modelConstants.js": "<rootDir>/server/constants/modelConstants.ts",
  }
};